config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/projects'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Portfolio", root_path, class: "navbar-brand px-3" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", pages_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Projects", pages_projects_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex px-3">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <div class= "conatiner my-3 px-4" >
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>Write a story on how you became a developer and what made you pursue this field, share your history, experiences, hobbies and aspirations</p>

app/views/pages/home.html.erb
<h1>Cris Jeanne Pador</h1>
<h3>Introduction</h3>
<p>Put content here</p>
<h3>Projects Overview</h3>
<p>Put content here</p>
<h3>Technical Skills</h3>
<p>Put content here</p>
<h3>Professional Experience</h3>
<p>Put content here</p>
<h3>Certifications</h3>
<p>Put content here</p>
<h3>Interpersonal Skills</h3>
<p>Put content here</p>

app/views/pages/projects.html.erb
<h1>Personal Projects</h1>
<p>Put Photo Samples 3 per project</p>
<p>Provide Description on what the project is all about</p>
<p>Provide Live Demo Links for Deployed Projects</p>